name: MusicResearcher

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Setup golangci-lint
      uses: golangci/golangci-lint-action@v3.7.0
      with:
        version: v1.55.0
        args: --verbose


  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Authenticate
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Test
      run: go test -v -race -covermode=atomic -coverprofile=coverage.out ./...

    - name: Upload coverage
      uses: codecov/codecov-action@v3